"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1g53eeyo74)-t(ffixb=j#p@)_n8=3$$#e#eztli9@9w%cee*m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '111.230.51.186',
    '127.0.0.1'
    ]

LOGIN_REDIRECT_URL = '/dashboard/'

LOGIN_URL = '/login/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Situation_Awareness_Platform',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['Situation_Awareness_Platform/template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'situation_awareness_platform',
        'USER': 'admin',
        'PASSWORD': '1221123.g',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'Situation_Awareness_Platform.middleware.GeoIPMiddleware',
]

GEOIP_PATH = '/home/ubuntu/app/Situation_Awareness_Platform/libs/'

# Web 日志路径
apache_log = '/var/log/apache2/access.log'

# 爆破次数设定
burst_num = 30

# SQL 注入攻击匹配规则
sqlrule = "'|--|update|extractvalue|union|select|substr|information_schema".split(
    '|')
# XSS 跨站攻击匹配规则
xssrule = "script|iframe|javascript|onerror|onmouseover|/>".split('|')
# 木马后门 匹配规则
backrule = "eval|assert|system|shell_exec|passthru".split('|')

# Type 设置
attackType = {
    100: '无威胁',
    101: 'XSS跨站',
    102: 'SQL注入',
    103: '目录扫描',
    104: 'DoS攻击',
    105: '暴力破解',
    106: '木马后门',
    107: 'SSH爆破'
}

# 要监视是否正常运行的程序列表
process = ['apache', 'mysqld', 'vsftpd', 'sshd']

local_adapter = 'any'
local_coord = [-118.24368, 34.05223]
local_city = 'Beijing'

# 流量统计单位
stream_unit = 1024  # KB
# stream_unit = 1024 * 1024        # MB
# stream_unit = 1024 * 1024 * 1024 # GB

